<?php

namespace SaS\Util;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-05-10 at 10:08:40.
 */
class SignerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Signer
     */
    protected $signer;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->signer = new Signer(sha1('foo'));
    }

    public function testSign_SimpleValue() {
        $this->assertEquals(hash_hmac('sha1', 'bar=foo;', sha1('foo')), $this->signer->sign(['bar' => 'foo']));
    }

    public function testSign_Array() {
        $data = [
            'foo' => 'bar',
            'asdf' => 'jkl',
        ];

        $expectedHMAC = hash_hmac('sha1', 'foo=bar;asdf=jkl;', sha1('foo'));

        $this->assertEquals($expectedHMAC, $this->signer->sign($data));
    }

    /**
     * @expectedException \LogicException
     */
    public function testSign_NestedArray() {
        $data = [
            'foo' => 'bar',
            'asdf' => [
                'asdf' => 'foo'
            ],
        ];

        $this->signer->sign($data);
    }
}
