<?php

namespace SaS\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-04-29 at 21:37:22.
 */
class ControlerManagerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ControlerManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ControlerManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SaS\Controller\ControlerManager::getControllers
     * @todo   Implement testGetControllers().
     */
    public function testGetControllers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SaS\Controller\ControlerManager::setControllers
     * @todo   Implement testSetControllers().
     */
    public function testSetControllers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SaS\Controller\ControlerManager::addControler
     * @todo   Implement testAddControler().
     */
    public function testAddControler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SaS\Controller\ControlerManager::registerControllers
     * @todo   Implement testRegisterControllers().
     */
    public function testRegisterControllers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SaS\Controller\ControlerManager::handleRequest
     * @todo   Implement testHandleRequest().
     */
    public function testHandleRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
