<?php

namespace SaS\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-04-29 at 21:26:55.
 */
class ResponseBuilderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ResponseBuilder
     */
    protected $builder;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->builder = new ResponseBuilder;
    }


    /**
     * 
     */
    public function testBuildErrorResponse() {
        $errors = [
                    [100, 'we got an error here'], 
                    [200, 'whoa, another error']
                  ];
        $code = 400;
        
        $response = $this->builder->buildErrorResponse($errors, $code);
        
        $this->assertEquals(400, $response->getStatusCode());
        
        $expectedDecodedContent = [
                                    ['code' => 100, 'message' => 'we got an error here'], 
                                    ['code' => 200, 'message' => 'whoa, another error' ]
                                  ];
        
        $this->assertSame($expectedDecodedContent, json_decode($response->getContent(), true));
        
        $this->assertSame('application/json', $response->headers->get('content-type'));
        
    }
    
    public function testBuildErrorResponse_ReturnsGivenResponse() {
        $response = new \Symfony\Component\HttpFoundation\Response;
        $this->assertSame($response, $this->builder->buildErrorResponse([], 404, $response)); //same means same object, not necessarily structural equality
    }

}
